
name: colorchangerPDF 
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel

      - name: Set version from release tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Using GitHub Release tag: $TAG"
          if [ -f pyproject.toml ]; then
            sed -i '' "s/^version = .*/version = \"$TAG\"/" pyproject.toml
          fi
          if [ -f colorchangerPDF/__version__.py ]; then
            echo "__version__ = '$TAG'" > colorchangerPDF/__version__.py
          fi

      - name: Build release distributions
        run: python -m build --sdist --wheel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write
    environment:
      name: pypi

    steps:
      - name: Download release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

    
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/

# Project references
# GitHub: https://github.com/Abdullah-js/colorchangerPDF/
# PyPI: https://pypi.org/project/colorchangerPDF/
